config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  get 'sessions/index'
  # get 'customers/index'
  # get 'movies/index'
  # get 'movies/show/:id', to: "movies#show"
  get 'screens/index'
  # get 'theatres/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'theatres/movies/index'
  # Defines the root path route ("/")
  # root "articles#index"

  resources :movies
  resources :customers

  # resources :users
  # resources :sessions

  # get 'sessions/new'
  # post 'sessions/create'

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  # get 'users/new'
  # post 'users/create'
  # delete 'users/destroy'

  root "theatres#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
	belongs_to :theatre, optional:true
	belongs_to :movie, optional:true

#---------------------------- new work ------------------------------ 
	before_save :downcase_email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness:true ,format: { with: VALID_EMAIL_REGEX }


	PASSWORD_REGEX = /\A (?=.{6,})(?=.*\d)(?=.*[a-z])/x
  	has_secure_password
  	validates :password, length: { minimum: 6 }, allow_blank: true , :format => {:with => PASSWORD_REGEX, message: "at least 6 characters and must include one number and one letter."},unless: Proc.new { |a| a.password.blank? }

	def downcase_email
		self.email = email.downcase
	end

end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :theatre
end

app/models/movie.rb
class Movie < ApplicationRecord
	belongs_to :screen
	has_many :customers
	
	validates :name, presence:true, uniqueness:true
end

app/models/screen.rb
class Screen < ApplicationRecord
	has_one :movie
	has_many :customers, through: :movie
	belongs_to :theatre

	
	validates :screen_id, presence: true, uniqueness: true, numericality: true

# ----------------------------------Not for use--------------------------------
	# using scope
	# scope :created_before ,-> {where("created_at < ?", Date.today)}

	# def self.created_before
	# 	where("created_at < ?", Date.today)
	# end
# -----------------------------------------------------------------------------

end

app/models/theatre.rb
class Theatre < ApplicationRecord
	has_many :customers
	has_many :employees
	has_many :screens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include SessionsHelper
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    # ----------------------------------------------------------------
    # ------- used when we have to get all users of that movie--------
    # binding.pry
    # if params[:movie_id].present?
    #   @customers = Customer.where(movie_id:params[:movie_id])
    # else
    #   @customers =Customer.all
    # end
    # ----------------------------------------------------------------
  end

  def show
    # @customer =Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      sign_in @customer
      flash[:success] = "Welcome, you have successfully created your account !"
      redirect_to screens_index_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @customer = Customer.find(params[:customer_id])
    @movie = Movie.find(params[:movie_id])
    @theatre = Theatre.find(params[:theatre_id])

  end

  def update
    @customer = Customer.find(params[:customer_id])
    if @customer.update(book_ticket)
      redirect_to sessions_index_path
    end
  end


    # ----------------------------------------------------

    # @movie = Movie.find_by(id: params[:movie_id])
    
    # @customer = @movie.customers.build(customer_params)
    # @customer.save
    # redirect_to users_path
    # render plain: "Ticket Booked"

    #  ---------------------------------------------------



  private

  #-------- to book the ticket --------

    def book_ticket
      params.permit(:theatre_id,:movie_id)
    end

  # ------- to create a new customer/sign_up --------

    def customer_params
      params.require(:customer).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    # ----------- not for use ------------
    # # @movies =Movie.all
    # @movie = Movie.released_before
  end

  def show
    @movie= Movie.find(params[:id])
  end

  def new
    @movie =Movie.new
  end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  def index
    @screens = Screen.all
  end

  def show
    @screen = Screen.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    entered_email = params[:session][:email].downcase
    
    # checking whether the email is nil or not
    if entered_email != ""
      customer = Customer.find_by(email: params[:session][:email].downcase)

      # if customer is present in the database
      if customer 
        # checking whether the details of customer entered are authentic or not
        if customer && customer.authenticate(params[:session][:password])
          sign_in customer
          flash[:success] = "Welcome, you are signed in ..."
          redirect_to screens_index_path

        # else
        #   flash[:error] = "Password does not match"
        #   redirect_to sessions_new_path
        end

      else
        flash[:error]='Email does not exist'
        redirect_to sessions_new_path
      end

    else
      flash[:error]='Fields can not be blank'
      redirect_to sessions_new_path
    end
  end

  def destroy
    sign_out if signed_in?
    redirect_to root_path
    flash[:info] = "Signed Out !"
  end

end

# ----------------------------------------------------------------

# -----------------------------------------------------------------
        # @customers =Customer.all
        # entered_email = params[:session][:email].downcase    
        #elsif customer == nil
        #flash[:error]="Email field can't be blank"
        #redirect_to sessions_new_path    

        # elsif !customer.present?  
        #   flash[:error]='Email does not exist.'
        #redirect_to sessions_new_path   

# -----------------------------------------------------------------

# ------------------------ previous work --------------------------


  #   user = User.find_by(email: params[:session][:email])
  #   # user.present?
  #   if user && user.authenticate(params[:session][:password])
  #     # session[:user_id] = user.id
  #     sign_in user
  #     redirect_to screens_index_path
  
  #   else
  #     # flash[:danger]='Invalid credentials'
  #     render 'new'
  #   end
  # end




  # def current_user
  #   @current_user = @current_user || User.find_by(id: session[:user_id])
  # end

  # def signed_in?
  #   !current_user.nil?
  # end


  # def sign_in(user)
  #   session[:user_id] = user.id
  # end
# ---------------------------------------------------------------

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  def index
    @theatre = Theatre.all
  end

  def show
    @theatre = Theatre.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper	

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(customer)
		session[:customer_id] = customer.id
	end
	
	def current_customer
		@current_customer = @current_customer || Customer.find_by(id: session[:customer_id])
	end

	def signed_in?
		!current_customer.nil?
	end

	def sign_out
		session.delete(:customer_id)
		@current_customer = nil
	end
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/customers/edit.html.erb
<!-- Booking the ticket of movie -->

<div style="background-color: lavender; text-align: center;border-style: solid;padding: 20px;">
<h3>Book Your Ticket :</h3>
<% if signed_in? %>
	<div>	
		<%= form_for @customer, url: customer_path(customer_id: current_customer.id, theatre_id: @movie.screen.theatre.id, movie_id: @movie.id) do %>


 			<%= submit_tag "Book Ticket" %>
	</div>
		<% end %>
<% else %>
	<h3>Sign in first ...</h3>
<% end %>
<br>
<%= link_to "Back to Home page", root_path %>
</div>


<!-- not for use	<%= label_tag :name %>
<%= text_field_tag :name %> -->

app/views/customers/index.html.erb
<h1>Customers :</h1>
<% @customers.each do |c| %>
	<ul>
		<li>
			<%= c.name %>
		</li>
	</ul>
	
<% end %>
<br>
<%= link_to "Back to Home page", root_path %>

app/views/customers/new.html.erb
<div style="background-color: lavender; text-align: center;border-style: solid; padding: 20px;">
<h1>Sign Up</h1>
<hr>
<div>
	<%= form_for @customer do |f| %>


		<%= f.label :email %>
		<br>
		<%= f.email_field :email %>
		<div class="error_message">
			<% @customer.errors.full_messages_for(:email).each do |msg| %>
		<%= msg %>
		<% end %>
		</div>
		

		<br>

		<%= f.label :password %>
		<br>
		<%= f.password_field :password %>
		<div class="error_message">
			<% @customer.errors.full_messages_for(:password).each do |msg| %>
		<%= msg %>
		<% end %>
		</div>
		

		<br>

		<%= f.label :password_confirmation %>
		<br>
		<%= f.password_field :password_confirmation %>
		<div class="error_message">
			<% @customer.errors.full_messages_for(:password_confirmation).each do |msg| %>
		<%= msg %>
		<% end %>
		</div>
		
		<br>
		<br>
		<%= f.submit "Sign up!" %>
	<% end %>
</div>
<br>
<%= link_to "Back to Home page", root_path %>
</div>

app/views/customers/show.html.erb
<%= @customer.email %>

app/views/layouts/_flash.html.erb
<% if flash.any? %>

<% flash.each do |message_type,message| %>
<div style="background-color: skyblue;text-align: center;size: 20px;">
	 <%= message %>
	</div>


<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheatreApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <style>
    .error_message{
      color: red;
    }
  </style>
</head>

<body style="background-color:lightblue;">
  <h2 style="text-align: center;margin: 0px;padding: 20px;">Welcome to Theatre App</h2>
  <div style="padding: 15px;">
  <% if signed_in? %>
  <%= link_to "Sign Out !", sessions_destroy_path %>
  <% else %>
  <%= link_to "Sign In!", sessions_new_path %>
  <% end %>
  </div>
  <%= yield %>

  <br>

  <h3 style="position: fixed;left: 0;bottom: 0;width: 100%;background-color: red;color: white; text-align: center">This website is developed by Deepak</h3>
</body>
</html>

app/views/movies/index.html.erb
 <h1>Movies:</h1>
<% @movies.each do |m| %>
	<ul>
		<li>
			<h2>
				<%= link_to m.name %>
			</h2>
		</li>
	</ul>
<% end %>


<!-- previous work	<h3><%= link_to "Book Ticket" %></h3>
	<h3>
		<%= link_to "customers" ,customers_path(m.id) %>
	</h3>
	<hr>
 -->

app/views/movies/show.html.erb
<div style="background-color: lavender; text-align: center;border-style: solid;padding: 20px;">
<h1><%= "Movie : #{@movie.name}" %></h1>

<% if signed_in? %>

<%= link_to "Book Your Ticket",edit_customer_path(customer_id:current_customer.id,theatre_id: @movie.screen.theatre.id, movie_id: @movie.id) %>
<br><br>

<% else %>
 
 <%= link_to "Sign In to book your ticket", sessions_new_path %>


 <br>
 <br>

 <% end %>
<%= link_to "Back to Home page", root_path %>
</div>

app/views/screens/index.html.erb
<%= render "layouts/flash" %>
<div style="background-color: lavender; text-align: center;border-style: solid;padding: 20px;">

<h1>Screens :</h1><hr>

	<% @screens.each do |s| %>

	
		<%= link_to "Screen : #{s.screen_id}", movie_path(s.id) %>
		<br>
		<br>

<% end %>
<br>
<%= link_to "Back to Home page", root_path %>
</div>

app/views/theatres/index.html.erb
<div style="background-color: lavender; text-align: center; padding: 20px;">
<%= render "layouts/flash" %>
<h1>Theatre App</h1>

<% @theatre.each do |t| %>
<h1 style="text-decoration-color: none;">
	<%= link_to t.name, screens_index_path %>
</h1>
<% end %>




</div>




<!-- ----------- Not Used --------- -->

<!-- <p>
	<%= link_to "Customers" ,customers_path %>

	<% if signed_in? %>
	<%= link_to "Sign Out", sessions_destroy_path %>
	<% else %>
	<%= link_to "Sign In!", sessions_new_path %>
<% end %>
</p> -->
	